# Generated by Django 2.0.5 on 2018-11-15 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent_Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Career_Path',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(choices=[('central_scheduling', 'Central Scheduling'), ('customer_service', 'Customer Service'), ('customer_solutions', 'Customer Solutions'), ('RECs_&_rebates', 'RECs & Rebates'), ('customer_relations', 'Customer Relations')], max_length=200)),
                ('sub_team', models.CharField(blank=True, choices=[('inbound', 'Inbound'), ('auxiliary', 'Auxiliary'), ('super_agent', 'Super Agent'), ('customer_solutions', 'Customer Solutions'), ('service', 'Service'), ('customer_service', 'Customer Service'), ('transfer', 'Transfer'), ('resolution', 'Resolution'), ('customer_solutions_admin', 'Customer Solutions Admin'), ('RECs_&_rebates', 'RECs & Rebates'), ('inbound_outbound', 'Inbound/Outbound'), ('email_admin', 'Email Admin'), ('documents', 'Documents')], max_length=200, null=True)),
                ('tier', models.CharField(choices=[('rep_1', 'Rep 1'), ('rep_2', 'Rep 2'), ('rep_3', 'Rep 3'), ('specialist_1', 'Specialist 1'), ('specialist_2', 'Specialist 2'), ('specialist_3', 'Specialist 3'), ('team_lead', 'Team Lead')], max_length=200)),
                ('tier_level', models.FloatField(choices=[(1.1, 'Tier 1.1'), (2.1, 'Tier 2.1'), (2.2, 'Tier 2.2'), (2.3, 'Tier 2.3'), (3.1, 'Tier 3.1'), (3.2, 'Tier 3.2'), (3.3, 'Tier 3.3')])),
                ('description', models.CharField(max_length=1000)),
                ('qa', models.FloatField(blank=True, choices=[(0, '0%'), (1, '1%'), (2, '2%'), (2.5, '2.5%'), (3, '3%'), (4, '4%'), (5, '5%'), (6, '6%'), (7, '7%'), (8, '8%'), (9, '9%'), (10, '10%'), (15, '15%'), (20, '20%'), (25, '25%'), (30, '30%'), (35, '35%'), (40, '40%'), (45, '45%'), (50, '50%'), (55, '55%'), (60, '60%'), (65, '65%'), (70, '70%'), (75, '75%'), (80, '80%'), (85, '85%'), (90, '90%'), (95, '95%'), (100, '100%')], null=True)),
                ('productivity', models.FloatField(blank=True, choices=[(0, '0%'), (1, '1%'), (2, '2%'), (2.5, '2.5%'), (3, '3%'), (4, '4%'), (5, '5%'), (6, '6%'), (7, '7%'), (8, '8%'), (9, '9%'), (10, '10%'), (15, '15%'), (20, '20%'), (25, '25%'), (30, '30%'), (35, '35%'), (40, '40%'), (45, '45%'), (50, '50%'), (55, '55%'), (60, '60%'), (65, '65%'), (70, '70%'), (75, '75%'), (80, '80%'), (85, '85%'), (90, '90%'), (95, '95%'), (100, '100%')], null=True)),
                ('aht', models.FloatField(blank=True, null=True)),
                ('aph', models.FloatField(blank=True, null=True)),
                ('adh', models.FloatField(blank=True, choices=[(0, '0%'), (1, '1%'), (2, '2%'), (2.5, '2.5%'), (3, '3%'), (4, '4%'), (5, '5%'), (6, '6%'), (7, '7%'), (8, '8%'), (9, '9%'), (10, '10%'), (15, '15%'), (20, '20%'), (25, '25%'), (30, '30%'), (35, '35%'), (40, '40%'), (45, '45%'), (50, '50%'), (55, '55%'), (60, '60%'), (65, '65%'), (70, '70%'), (75, '75%'), (80, '80%'), (85, '85%'), (90, '90%'), (95, '95%'), (100, '100%')], null=True)),
                ('availability', models.FloatField(blank=True, null=True)),
                ('error_rate', models.CharField(blank=True, max_length=500, null=True)),
                ('efficiency', models.FloatField(blank=True, null=True)),
                ('duration', models.FloatField(blank=True, default=90.0, null=True)),
                ('nps', models.FloatField(blank=True, null=True)),
                ('field_qa_nps_score', models.FloatField(blank=True, null=True)),
                ('pay_rate', models.FloatField(choices=[(12.0, '$12.00'), (13.0, '$13.00'), (13.25, '$13.25'), (13.75, '$13.75'), (14.0, '$14.00'), (14.25, '$14.25'), (14.5, '$14.50')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee_List',
            fields=[
                ('badge_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('business_title', models.CharField(max_length=500)),
                ('supervisor_badge', models.IntegerField(null=True)),
                ('supervisor_name', models.CharField(max_length=200)),
                ('hire_date', models.DateTimeField(null=True)),
                ('team', models.CharField(max_length=200)),
                ('sub_team', models.CharField(max_length=200)),
                ('tier', models.CharField(max_length=200)),
                ('terminated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='agent_skills',
            name='badge_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Soft_Skills.Employee_List'),
        ),
        migrations.AddField(
            model_name='agent_skills',
            name='skill_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Soft_Skills.Career_Path'),
        ),
    ]
