# Generated by Django 2.0.5 on 2018-11-16 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Soft_Skills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_list',
            name='sub_team',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
