# Generated by Django 2.0.4 on 2018-05-07 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Luna', '0002_auto_20180507_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerpath',
            name='adh',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='careerpath',
            name='aht',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='careerpath',
            name='aph',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='careerpath',
            name='availability',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='careerpath',
            name='efficiency',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='careerpath',
            name='error_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='careerpath',
            name='nps',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='careerpath',
            name='qa',
            field=models.IntegerField(blank=True, choices=[(60, '60%'), (70, '70%'), (80, '80%')], null=True),
        ),
    ]
