# Generated by Django 2.0.4 on 2018-05-07 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Luna', '0003_auto_20180507_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerpath',
            name='position',
            field=models.CharField(choices=[('RP1', 'Representative 1'), ('RP2', 'Representative 2'), ('RP3', 'Representative 3'), ('SP1', 'Specialist 1'), ('SP2', 'Specialist 2'), ('SP3', 'Specialist 3'), ('TL', 'Team Lead')], default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='careerpath',
            name='function',
            field=models.CharField(blank=True, choices=[('IB', 'Inbound'), ('AUX', 'Auxiliary'), ('SA', 'Super Agent'), ('SER', 'Service'), ('CSR', 'Customer Service'), ('SP1', 'Specialist 1'), ('SA', 'Super Agent'), ('RAR', 'RECs and Rebates'), ('IBO', 'Inbound / Outbound'), ('EA', 'Email Admins'), ('DOC', 'Documents')], max_length=200, null=True),
        ),
    ]
