# Generated by Django 2.0.4 on 2018-05-07 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Luna', '0004_auto_20180507_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerpath',
            name='field_qa_nps_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
