# Generated by Django 2.0.4 on 2018-05-07 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Luna', '0005_careerpath_field_qa_nps_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerpath',
            name='department',
            field=models.CharField(choices=[('Real Time Scheduling', 'Real Time Scheduling'), ('Customer Service', 'Customer Service'), ('Customer Solutions', 'Customer Solutions'), ('RECs and Rebates', 'RECs & Rebates'), ('Relations', 'Relations')], max_length=3),
        ),
        migrations.AlterField(
            model_name='careerpath',
            name='function',
            field=models.CharField(blank=True, choices=[('IB', 'Inbound'), ('AUX', 'Auxiliary'), ('SA', 'Super Agent'), ('SER', 'Service'), ('Customer Service', 'Customer Service'), ('SP1', 'Specialist 1'), ('SA', 'Super Agent'), ('RECs and Rebates', 'RECs and Rebates'), ('IBO', 'Inbound / Outbound'), ('EA', 'Email Admins'), ('DOC', 'Documents')], max_length=200, null=True),
        ),
    ]
