# Generated by Django 2.0.4 on 2018-05-07 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Luna', '0006_auto_20180507_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerpath',
            name='department',
            field=models.CharField(choices=[('Real Time Scheduling', 'Real Time Scheduling'), ('Customer Service', 'Customer Service'), ('Customer Solutions', 'Customer Solutions'), ('RECs and Rebates', 'RECs & Rebates'), ('Relations', 'Relations')], max_length=200),
        ),
    ]
