# Generated by Django 2.0.4 on 2018-05-08 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Luna', '0007_auto_20180507_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerpath',
            name='productivity',
            field=models.IntegerField(blank=True, choices=[(0, '0%'), (10, '10%'), (20, '20%'), (30, '30%'), (40, '40%'), (50, '50%'), (60, '60%'), (70, '70%'), (80, '80%'), (90, '90%'), (100, '100%')], null=True),
        ),
        migrations.AlterField(
            model_name='careerpath',
            name='department',
            field=models.CharField(choices=[('real_time_scheduling', 'Real Time Scheduling'), ('customer_service', 'Customer Service'), ('customer_solutions', 'Customer Solutions'), ('recs_and_rebates', 'RECs & Rebates'), ('relations', 'Relations')], max_length=200),
        ),
        migrations.AlterField(
            model_name='careerpath',
            name='function',
            field=models.CharField(blank=True, choices=[('inbound', 'Inbound'), ('auxiliary', 'Auxiliary'), ('super_agent', 'Super Agent'), ('service', 'Service'), ('customer_service', 'Customer Service'), ('specialist_1', 'Specialist 1'), ('recs_and_rebates', 'RECs and Rebates'), ('inbound_outbound', 'Inbound / Outbound'), ('email_admin', 'Email Admins'), ('documents', 'Documents')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='careerpath',
            name='position',
            field=models.CharField(choices=[('representative_1', 'Representative 1'), ('representative_2', 'Representative 2'), ('representative_3', 'Representative 3'), ('specialist_1', 'Specialist 1'), ('specialist_2', 'Specialist 2'), ('specialist_3', 'Specialist 3'), ('team_lead', 'Team Lead')], max_length=200),
        ),
        migrations.AlterField(
            model_name='careerpath',
            name='qa',
            field=models.IntegerField(blank=True, choices=[(0, '0%'), (10, '10%'), (20, '20%'), (30, '30%'), (40, '40%'), (50, '50%'), (60, '60%'), (70, '70%'), (80, '80%'), (90, '90%'), (100, '100%')], null=True),
        ),
    ]
