# Generated by Django 2.0.4 on 2018-05-08 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Luna', '0008_auto_20180508_1201'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomatorTasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='careerpath',
            name='function',
            field=models.CharField(blank=True, choices=[('inbound', 'Inbound'), ('auxiliary', 'Auxiliary'), ('super_agent', 'Super Agent'), ('service', 'Service'), ('customer_service', 'Customer Service'), ('specialist_1', 'Specialist 1'), ('recs_and_rebates', 'RECs & Rebates'), ('inbound_outbound', 'Inbound / Outbound'), ('email_admin', 'Email Admins'), ('documents', 'Documents')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='careerpath',
            name='productivity',
            field=models.IntegerField(blank=True, choices=[(0, '0%'), (10, '10%'), (20, '20%'), (30, '30%'), (40, '40%'), (50, '50%'), (60, '60%'), (70, '70%'), (75, '75%'), (80, '80%'), (90, '90%'), (100, '100%')], null=True),
        ),
        migrations.AlterField(
            model_name='careerpath',
            name='qa',
            field=models.IntegerField(blank=True, choices=[(0, '0%'), (10, '10%'), (20, '20%'), (30, '30%'), (40, '40%'), (50, '50%'), (60, '60%'), (70, '70%'), (75, '75%'), (80, '80%'), (90, '90%'), (100, '100%')], null=True),
        ),
    ]
