# Generated by Django 2.0.4 on 2018-05-08 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Luna', '0010_auto_20180508_1549'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AutomatorTasks',
            new_name='AutomatorTask',
        ),
    ]
