# Generated by Django 2.0.4 on 2018-05-10 20:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Luna', '0011_auto_20180508_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept', models.TextField()),
                ('up_votes', models.IntegerField(default=0)),
                ('down_votes', models.IntegerField(default=0)),
                ('submit_date', models.DateField(default=datetime.datetime(2018, 5, 10, 20, 14, 44, 65766, tzinfo=utc))),
            ],
        ),
    ]
