# Generated by Django 2.0.4 on 2018-05-10 20:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Luna', '0012_idea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='submit_date',
            field=models.DateField(default=datetime.datetime(2018, 5, 10, 20, 16, 21, 578900, tzinfo=utc)),
        ),
    ]
