# Generated by Django 2.0.4 on 2018-05-10 22:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Luna', '0013_auto_20180510_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='submit_date',
            field=models.DateField(default=datetime.datetime(2018, 5, 10, 22, 24, 2, 237178, tzinfo=utc)),
        ),
    ]
