# Generated by Django 2.0.5 on 2018-05-15 16:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Luna', '0014_auto_20180510_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='submit_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
