# Generated by Django 2.0.5 on 2018-06-05 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Luna', '0016_auto_20180605_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerpath',
            name='duration',
            field=models.IntegerField(blank=True, default=90, null=True),
        ),
    ]
