# Generated by Django 2.0.6 on 2018-09-14 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Luna', '0017_auto_20180605_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerpath',
            name='function',
            field=models.CharField(blank=True, choices=[('inbound', 'Inbound'), ('auxiliary', 'Auxiliary'), ('super_agent', 'Super Agent'), ('service', 'Service'), ('customer_service', 'Customer Service'), ('customer_solutions_admin', 'Customer Solutions Admin'), ('recs_and_rebates', 'RECs & Rebates'), ('inbound_outbound', 'Inbound / Outbound'), ('email_admin', 'Email Admins'), ('documents', 'Documents')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='careerpath',
            name='pay_rate',
            field=models.FloatField(choices=[(12.0, '$12.00'), (13.0, '$13.00'), (13.25, '$13.25'), (13.75, '$13.75'), (14.0, '$14.00'), (14.25, '$14.25'), (14.5, '$14.50')]),
        ),
        migrations.AlterField(
            model_name='careerpath',
            name='position',
            field=models.CharField(choices=[('rep_1', 'Rep 1'), ('rep_2', 'Rep 2'), ('rep_3', 'Rep 3'), ('specialist_1', 'Specialist 1'), ('specialist_2', 'Specialist 2'), ('specialist_3', 'Specialist 3'), ('team_lead', 'Team Lead')], max_length=200),
        ),
    ]
