# Generated by Django 2.0.6 on 2018-09-06 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Luna', '0017_auto_20180605_1052'),
    ]

    operations = [
        migrations.CreateModel(
            name='buyout_calc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_buyout', models.DecimalField(decimal_places=2, max_digits=3)),
                ('default_price', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
        migrations.AlterField(
            model_name='careerpath',
            name='function',
            field=models.CharField(blank=True, choices=[('inbound', 'Inbound'), ('auxiliary', 'Auxiliary'), ('super_agent', 'Super Agent'), ('service', 'Service'), ('customer_service', 'Customer Service'), ('customer_solutions_admin', 'Customer Solutions Admin'), ('recs_and_rebates', 'RECs & Rebates'), ('inbound_outbound', 'Inbound / Outbound'), ('email_admin', 'Email Admins'), ('documents', 'Documents')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='careerpath',
            name='pay_rate',
            field=models.FloatField(choices=[(12.0, '$12.00'), (13.0, '$13.00'), (13.25, '$13.25'), (13.75, '$13.75'), (14.0, '$14.00'), (14.25, '$14.25'), (14.5, '$14.50')]),
        ),
    ]
