# Generated by Django 2.0.6 on 2018-09-06 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Luna', '0018_auto_20180906_1509'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='buyout_calc',
            new_name='buyout_calc_model',
        ),
    ]
