# Generated by Django 2.0.5 on 2018-06-05 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Luna', '0018_vcaaslogin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vcaaslogin',
            old_name='web_portal',
            new_name='vcaas_password',
        ),
    ]
