# Generated by Django 2.0.5 on 2018-06-21 18:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Luna', '0019_auto_20180605_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automatortask',
            name='day',
        ),
        migrations.RemoveField(
            model_name='automatortask',
            name='id',
        ),
        migrations.AddField(
            model_name='automatortask',
            name='created_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='automatortask',
            name='data_format_google_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='automatortask',
            name='data_format_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='automatortask',
            name='data_source_google_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='automatortask',
            name='data_source_type',
            field=models.CharField(blank=True, choices=[('sql', 'SQL'), ('sql_command', 'SQL Command'), ('python', 'Python')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='automatortask',
            name='dynamic_file_name',
            field=models.CharField(blank=True, help_text='<a href="http://strftime.org/">Click Here</a> for a formatting legend', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='automatortask',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='automatortask',
            name='file_storage_google_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='automatortask',
            name='file_storage_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='automatortask',
            name='recurrence_minutes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='automatortask',
            name='recurrence_month_days',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='automatortask',
            name='recurrence_months',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='automatortask',
            name='recurrence_start_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='automatortask',
            name='recurrence_times',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='automatortask',
            name='recurrence_type',
            field=models.CharField(blank=True, choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='automatortask',
            name='recurrence_week_days',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='automatortask',
            name='recurrence_weeks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='automatortask',
            name='spreadsheet_end_column_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='automatortask',
            name='spreadsheet_end_row_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='automatortask',
            name='spreadsheet_sheet_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='automatortask',
            name='spreadsheet_start_column_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='automatortask',
            name='spreadsheet_start_row_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='automatortask',
            name='task_id',
            field=models.IntegerField(blank=True, null=True, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='automatortask',
            name='task_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='automatortask',
            name='task_owner_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='automatortask',
            name='task_owner_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='automatortask',
            name='task_priority',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
