# Generated by Django 2.0.6 on 2018-09-15 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Luna', '0020_auto_20180914_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerpath',
            name='department',
            field=models.CharField(choices=[('central_scheduling', 'Central Scheduling'), ('customer_service', ''), ('customer_solutions', ''), ('recs_and_rebates', ''), ('relations', 'Relations')], max_length=200),
        ),
        migrations.AlterField(
            model_name='careerpath',
            name='function',
            field=models.CharField(blank=True, choices=[('inbound', 'Inbound'), ('auxiliary', 'Auxiliary'), ('super_agent', 'Super Agent'), ('service', 'Service'), ('customer_service', 'Customer Service'), ('transfer', 'Transfer'), ('resolution', 'Resolution'), ('customer_solutions_admin', 'Admin'), ('recs_and_rebates', 'REC & Rebates'), ('inbound_outbound', 'Inbound / Outbound'), ('email_admin', 'Email Admins'), ('documents', 'Documents')], max_length=200, null=True),
        ),
    ]
