# Generated by Django 2.0.6 on 2018-09-15 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Luna', '0021_auto_20180914_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerpath',
            name='aht',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='careerpath',
            name='department',
            field=models.CharField(choices=[('central_scheduling', 'Central Scheduling'), ('customer_service', ''), ('customer_solutions', 'Customer Solutions'), ('recs_and_rebates', ''), ('relations', 'Relations')], max_length=200),
        ),
    ]
