# Generated by Django 2.0.6 on 2018-09-15 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Luna', '0022_auto_20180914_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerpath',
            name='aht',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
