# Generated by Django 2.0.6 on 2018-09-17 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Luna', '0024_auto_20180914_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerpath',
            name='aht',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='careerpath',
            name='error_rate',
            field=models.TextField(blank=True, null=True),
        ),
    ]
