# Generated by Django 2.0.6 on 2018-09-17 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Luna', '0025_auto_20180917_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerpath',
            name='error_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
