# Generated by Django 2.0.6 on 2018-09-17 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Luna', '0031_auto_20180917_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='careerpath',
            name='error_rate',
        ),
    ]
