# Generated by Django 2.0.6 on 2018-09-17 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Luna', '0032_remove_careerpath_error_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerpath',
            name='error_rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
