# Generated by Django 2.0.5 on 2018-09-18 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Luna', '0034_auto_20180918_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerpath',
            name='error_rate',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
