# Generated by Django 2.0.5 on 2018-09-19 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Luna', '0034_auto_20180918_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerpath',
            name='department',
            field=models.CharField(choices=[('central_scheduling', 'Central Scheduling'), ('customer_service', ''), ('customer_solutions', ''), ('RECs_&_rebates', ''), ('customer_relations', 'Customer Relations')], max_length=200),
        ),
        migrations.AlterField(
            model_name='careerpath',
            name='error_rate',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='careerpath',
            name='function',
            field=models.CharField(blank=True, choices=[('inbound', ' - Inbound'), ('auxiliary', ' - Auxiliary'), ('super_agent', ' - Super Agent'), ('customer_solutions', 'Customer Solutions'), ('service', ' - Service'), ('customer_service', 'Customer Service'), ('transfer', 'Transfer'), ('resolution', 'Resolution'), ('customer_solutions_admin', 'Customer Solutions Admin'), ('RECs_&_rebates', 'RECs & Rebates'), ('inbound_outbound', ' - Inbound / Outbound'), ('email_admin', ' - Email Admins'), ('documents', ' - Documents')], max_length=200, null=True),
        ),
    ]
