# Generated by Django 2.0.5 on 2018-10-04 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Luna', '0035_auto_20180918_1133'),
        ('Luna', '0035_auto_20180919_1739'),
    ]

    operations = [
    ]
