# Generated by Django 2.0.5 on 2018-10-10 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Luna', '0036_merge_20181004_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerpath',
            name='function',
            field=models.CharField(blank=True, choices=[('inbound', ' - Inbound'), ('auxiliary', ' - Auxiliary'), ('super_agent', ' - Super Agent'), ('customer_solutions', 'Customer Solutions'), ('service', ' - Service'), ('customer_service', 'Customer Service'), ('transfer', 'Transfer'), ('resolution', 'Resolution'), ('customer_solutions_admin', 'Customer Solutions Admin'), ('RECs_&_rebates', 'RECs & Rebates'), ('inbound_outbound', ' - Inbound/Outbound'), ('email_admin', ' - Email Admin'), ('documents', ' - Documents')], max_length=200, null=True),
        ),
    ]
