# Generated by Django 2.0.5 on 2018-11-15 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Luna', '0019_auto_20180906_1522'),
        ('Luna', '0037_auto_20181009_2010'),
    ]

    operations = [
    ]
