# Generated by Django 2.1.3 on 2018-11-20 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Luna', '0037_auto_20181009_2010'),
        ('Luna', '0019_auto_20180906_1522'),
    ]

    operations = [
    ]
