# Generated by Django 2.0.7 on 2018-07-16 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coin_sharing_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='coin_status',
        ),
    ]
