# Generated by Django 2.0.7 on 2018-07-19 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coin_sharing_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='COIN_STATUS',
            new_name='coin_stat',
        ),
        migrations.RenameModel(
            old_name='COIN_TRANSACTION',
            new_name='coin_trans',
        ),
    ]
