# Generated by Django 2.0.7 on 2018-08-02 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coin_sharing_app', '0004_auto_20180801_1344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='total',
            new_name='transition',
        ),
        migrations.RemoveField(
            model_name='status',
            name='create_at',
        ),
    ]
