# Generated by Django 2.0.7 on 2018-08-02 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin_sharing_app', '0005_auto_20180802_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='void_note',
            field=models.BooleanField(default=False),
        ),
    ]
