# Generated by Django 2.0.7 on 2018-08-02 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coin_sharing_app', '0006_transaction_void_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='void_note',
            new_name='bad_comment',
        ),
    ]
