# Generated by Django 2.0.7 on 2018-08-02 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coin_sharing_app', '0007_auto_20180802_0935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='transition',
            new_name='to_accept',
        ),
    ]
