# Generated by Django 2.0.7 on 2018-08-02 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin_sharing_app', '0008_auto_20180802_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='annonymous',
            field=models.BooleanField(default=False),
        ),
    ]
