# Generated by Django 2.0.7 on 2018-08-03 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coin_sharing_app', '0009_transaction_annonymous'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='annonymous',
            new_name='anonymous',
        ),
    ]
