# Generated by Django 2.0.7 on 2018-08-03 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin_sharing_app', '0010_auto_20180803_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='accept',
            field=models.BooleanField(default=False),
        ),
    ]
