SELECT
    BADGE,
    NAME,
    SUPERVISOR,
    SUM(MIN_WORKED) AS MIN_WORKED,
    SUM(BREAKS) AS BREAKS,
    SUM(ACTIVITY_TIME) AS ACTIVITY_TIME,
    SUM(TRAINING_TIME) AS TRAINING_TIME,
    SUM(MEETING_TIME) AS MEETING_TIME,
    SUM(HUDDLE_TIME) AS HUDDLE_TIME,
    SUM(PROJECT_TIME) AS PROJECT_TIME
FROM VSLR.D_POST_INSTALL.V_SREC_AGENT_PRODUCTIVITY
WHERE DAYOFWEEK(REPORT_DATE) BETWEEN 1 AND 5
AND REPORT_DATE BETWEEN Previous_DAY(DATEADD('d',-7,DATE_TRUNC('d',CURRENT_TIMESTAMP::TIMESTAMP_NTZ)),'su')
                        AND NEXT_DAY(DATEADD('d',-7,DATE_TRUNC('d',CURRENT_TIMESTAMP::TIMESTAMP_NTZ)),'sa')
AND BADGE = '{badge}'
GROUP BY BADGE, NAME, SUPERVISOR
;

SELECT
    TO_VARCHAR(PREVIOUS_DAY(DATEADD('d', -7,DATE_TRUNC('d',CURRENT_TIMESTAMP::TIMESTAMP_NTZ)),'SU'), 'MM/DD/YY') as REPORT_DATE
FROM D_POST_INSTALL.T_SREC_PROJECT_TIMES
WHERE EMPLOYEE_ID = '{badge}'
AND DAYOFWEEK(REPORT_DATE) BETWEEN 1 AND 5
GROUP BY REPORT_DATE
;

SELECT
    TO_VARCHAR(NEXT_DAY(DATEADD('d',-7,DATE_TRUNC('d',CURRENT_TIMESTAMP::TIMESTAMP_NTZ)),'sa'), 'MM/DD/YY') AS REPORT_DATE
FROM D_POST_INSTALL.T_SREC_PROJECT_TIMES
WHERE EMPLOYEE_ID = '{badge}'
AND DAYOFWEEK(REPORT_DATE) BETWEEN 1 AND 5
GROUP BY REPORT_DATE
;