# Generated by Django 2.0.5 on 2018-10-04 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='auth_employee',
            fields=[
                ('badge_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200)),
                ('authority', models.CharField(blank=True, choices=[('manager', 'Manager'), ('super', 'Supervisor'), ('tl', 'Team Lead'), ('employee', 'Employee')], max_length=200, null=True)),
                ('supervisor', models.CharField(blank=True, max_length=200, null=True)),
                ('terminated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting_Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project_Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('who_created', models.CharField(max_length=200)),
                ('expired', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project_Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('who_approved', models.CharField(max_length=200)),
                ('super_stamp', models.CharField(max_length=200)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Training_Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='auth_employee',
            name='meeting_time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='P_Tracker.Meeting_Time'),
        ),
        migrations.AddField(
            model_name='auth_employee',
            name='project_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='P_Tracker.Project_Name'),
        ),
        migrations.AddField(
            model_name='auth_employee',
            name='project_time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='P_Tracker.Project_Time'),
        ),
        migrations.AddField(
            model_name='auth_employee',
            name='training_time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='P_Tracker.Training_Time'),
        ),
    ]
