# Generated by Django 2.0.5 on 2018-10-04 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('P_Tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth_employee',
            name='supervisor',
            field=models.IntegerField(default=0),
        ),
    ]
