# Generated by Django 2.0.5 on 2018-10-10 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('P_Tracker', '0002_auto_20181010_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting_time',
            name='total_time',
            field=models.DecimalField(decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='project_time',
            name='total_time',
            field=models.DecimalField(decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='training_time',
            name='total_time',
            field=models.DecimalField(decimal_places=4, max_digits=6, null=True),
        ),
    ]
