# Generated by Django 2.0.5 on 2018-10-04 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('P_Tracker', '0002_auto_20181004_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth_employee',
            name='meeting_time',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='P_Tracker.Meeting_Time'),
        ),
        migrations.AlterField(
            model_name='auth_employee',
            name='project_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='P_Tracker.Project_Name'),
        ),
        migrations.AlterField(
            model_name='auth_employee',
            name='project_time',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='P_Tracker.Project_Time'),
        ),
        migrations.AlterField(
            model_name='auth_employee',
            name='training_time',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='P_Tracker.Training_Time'),
        ),
    ]
