# Generated by Django 2.0.5 on 2018-10-04 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('P_Tracker', '0003_auto_20181004_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auth_employee',
            name='meeting_time',
        ),
        migrations.RemoveField(
            model_name='auth_employee',
            name='project_name',
        ),
        migrations.RemoveField(
            model_name='auth_employee',
            name='project_time',
        ),
        migrations.RemoveField(
            model_name='auth_employee',
            name='training_time',
        ),
        migrations.AddField(
            model_name='meeting_time',
            name='auth_employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='P_Tracker.Auth_Employee'),
        ),
        migrations.AddField(
            model_name='project_name',
            name='auth_employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='P_Tracker.Auth_Employee'),
        ),
        migrations.AddField(
            model_name='project_time',
            name='auth_employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='P_Tracker.Auth_Employee'),
        ),
        migrations.AddField(
            model_name='training_time',
            name='auth_employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='P_Tracker.Auth_Employee'),
        ),
    ]
