# Generated by Django 2.0.5 on 2018-10-05 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('P_Tracker', '0004_auto_20181004_1442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auth_employee',
            old_name='authority',
            new_name='business_title',
        ),
        migrations.RenameField(
            model_name='project_name',
            old_name='auth_employee',
            new_name='business_title',
        ),
        migrations.AlterField(
            model_name='meeting_time',
            name='auth_employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='P_Tracker.Auth_Employee'),
        ),
        migrations.AlterField(
            model_name='project_name',
            name='business_title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='P_Tracker.Auth_Employee'),
        ),
        migrations.AlterField(
            model_name='project_time',
            name='auth_employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='P_Tracker.Auth_Employee'),
        ),
        migrations.AlterField(
            model_name='training_time',
            name='auth_employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='P_Tracker.Auth_Employee'),
        ),
    ]
