# Generated by Django 2.0.5 on 2018-10-17 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('P_Tracker', '0005_auto_20181015_0856'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting_time',
            old_name='reject',
            new_name='accept',
        ),
        migrations.RenameField(
            model_name='project_time',
            old_name='reject',
            new_name='accept',
        ),
        migrations.RenameField(
            model_name='training_time',
            old_name='reject',
            new_name='accept',
        ),
    ]
