# Generated by Django 2.0.5 on 2018-10-20 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('P_Tracker', '0007_auto_20181017_0742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting_time',
            name='reject',
        ),
        migrations.RemoveField(
            model_name='project_time',
            name='reject',
        ),
        migrations.RemoveField(
            model_name='training_time',
            name='reject',
        ),
        migrations.AlterField(
            model_name='meeting_time',
            name='accept',
            field=models.CharField(default=False, max_length=5),
        ),
        migrations.AlterField(
            model_name='project_time',
            name='accept',
            field=models.CharField(default=False, max_length=5),
        ),
        migrations.AlterField(
            model_name='training_time',
            name='accept',
            field=models.CharField(default=False, max_length=5),
        ),
    ]
