# Generated by Django 2.0.5 on 2018-10-22 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('P_Tracker', '0008_auto_20181019_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting_time',
            name='super_stamp',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='training_time',
            name='super_stamp',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
