# Generated by Django 2.0.5 on 2018-10-22 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('P_Tracker', '0009_auto_20181022_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting_time',
            name='accept',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project_time',
            name='accept',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='training_time',
            name='accept',
            field=models.BooleanField(default=False),
        ),
    ]
