# Generated by Django 2.0.5 on 2018-10-10 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('P_Tracker', '0014_auto_20181009_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting_time',
            name='total_hr',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='project_time',
            name='total_hr',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='training_time',
            name='total_hr',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='meeting_time',
            name='auth_employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='P_Tracker.Auth_Employee'),
        ),
        migrations.AlterField(
            model_name='project_name',
            name='badge_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='P_Tracker.Auth_Employee'),
        ),
        migrations.AlterField(
            model_name='project_time',
            name='auth_employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='P_Tracker.Auth_Employee'),
        ),
        migrations.AlterField(
            model_name='training_time',
            name='auth_employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='P_Tracker.Auth_Employee'),
        ),
    ]
