SELECT
    T.SERVICE_NUMBER,
    C.FULL_NAME,
    C.EMAIL,
    T.SERVICE_ADDRESS,
    T.SERVICE_CITY,
    T.SERVICE_STATE,
    T.SERVICE_ZIP_CODE
FROM VSLR.RPT.T_PROJECT AS T
INNER JOIN VSLR.RPT.T_CONTACT AS C ON C.CONTACT_ID =T.CONTRACT_SIGNER
WHERE T.SERVICE_NUMBER = '{service_number}';

SELECT
    P.SERVICE_NUMBER,
    C.SYSTEM_SIZE_ACTUAL_KW,
    P.REMAINING_CONTRACT_TERM
FROM VSLR.RPT.T_PROJECT AS P
INNER JOIN VSLR.RPT.T_CAD AS C ON P.PROJECT_ID = C.PROJECT_ID
WHERE P.SERVICE_NUMBER = '{service_number}'
