SELECT
      P.SERVICE_NAME,
      C.FULL_NAME,
      P.SERVICE_ADDRESS,
      P.SERVICE_CITY,
      P.SERVICE_STATE,
      P.SERVICE_ZIP_CODE,
      DATE_TRUNC('D', P.START_BILLING),
      P.UTILITY_COMPANY,
      U.BLENDED_RATE,
      CAD.CURRENT_ANNUAL_ENERGY_CONSUMPTION
FROM VSLR.RPT.T_PROJECT AS P
INNER JOIN VSLR.RPT.T_CONTACT AS C ON C.CONTACT_ID = P.CONTRACT_SIGNER
LEFT JOIN VSLR.D_POST_INSTALL.T_UTILITY_RATES AS U ON UPPER(U.UTILITY) = UPPER(P.UTILITY_COMPANY) AND U.STATE = P.SERVICE_STATE
LEFT JOIN VSLR.RPT.T_CAD AS CAD ON CAD.CAD_ID = P.PRIMARY_CAD
WHERE P.SERVICE_NUMBER = %s;

SELECT
    TO_VARCHAR(T.READ_DATE, 'Mon YYYY') AS MONTH_YEAR,
    T.ACTUAL_KWH,
    ROUND(T.ACTUAL_KWH * NVL(COALESCE (P.RATE_PER_KWH * POWER(1.029, TRUNC(DATEDIFF('D', DATE_TRUNC('D', P.START_BILLING),DATE_TRUNC('D', CURRENT_TIMESTAMP::TIMESTAMP_NTZ))/365)), T.CURRENT_RATE_KWH), 0), 2) AS VIVINT_SOLAR_BILL
FROM VSLR.FLEET.T_DAILY_ENERGY_WA AS T
INNER JOIN VSLR.RPT.T_PROJECT AS P ON P.PROJECT_ID = T.PROJECT_ID
LEFT JOIN VSLR.D_POST_INSTALL.T_UTILITY_RATES_SUMMARY AS U ON UPPER(U.UTILITY) = UPPER(P.UTILITY_COMPANY)
          AND U.STATE = P.SERVICE_STATE
WHERE P.SERVICE_NUMBER = %s;
AND T.READ_DATE BETWEEN TO_DATE(:startDate, 'MM/DD/YYYY') AND TO_DATE(:endDate,'MM/DD/YYYY')
AND T.LIFETIME_TOTAL_DAYS = (SELECT MAX(W.LIFETIME_TOTAL_DAYS) FROM VSLR.FLEET.T_DAILY_ENERGY_WA AS W WHERE W.PROJECT_ID = T.PROJECT_ID AND W.MONTH = T.MONTH AND W.YEAR = T.YEAR)
ORDER BY T.READ_DATE;