SELECT
    P.SERVICE_NUMBER,
<<<<<<< HEAD
<<<<<<< Updated upstream
=======
>>>>>>> Buyout_PrepayCalc
    CON.ESCALATOR,
    L.SYSTEM_SIZE_ACTUAL,
    C.SUN_HOURS_ACTUAL,
    P.RATE_PER_KWH,
    P.START_BILLING,
    P.RECORD_TYPE,
    P.CURRENT_ANNUAL_ENERGY_CONSUMPTION,
    P.REMAINING_CONTRACT_TERM,
    CON.CONTRACT_VERSION
FROM VSLR.RPT.T_PROJECT AS P
INNER JOIN VSLR.RPT.T_CAD AS C ON  C.CAD_ID = P.PRIMARY_CAD
INNER JOIN VSLR.RPT.T_CONTRACT AS CON ON P.PROJECT_ID = CON.PROJECT_ID
INNER JOIN VSLR.RPT.V_LOAN_DETAILS AS L ON P.PROJECT_NAME = L.PROJECT_NAME
WHERE P.SERVICE_NUMBER = '{service_number}'

-- SELECT
--       P.SERVICE_NUMBER,
--       D.ESCALATOR,
--       D.SYSTEM_SIZE_ACTUAL,
--       D.SUN_HOURS_ACTUAL,
--       P.RATE_PER_KWH,
--       D.START_BILLING,
--       CO.RECORD_TYPE,
--       D.CURRENT_ANNUAL_ENERGY_USAGE,
--       D.REMAINING_CONTRACT_TERM,
--       D.CONTRACT_VERSION
-- FROM SFRPT.MV_SYSTEM_DETAILS D
-- INNER JOIN SFRPT.T_DM_PROJECT P ON D.PROJECT_NAME = P.PROJECT_NAME
-- INNER JOIN SFRPT.T_DM_CONTRACT CO ON D.PROJECT_ID = CO.PROJECT_ID
-- WHERE P.SERVICE_NUMBER = :serviceNum;
<<<<<<< HEAD
=======
    C.ESCALATOR,
    CAD.SYSTEM_SIZE_ACTUAL_KW,
    CAD.SUN_HOURS_ACTUAL,
    P.RATE_PER_KWH,
    P.START_BILLING,
    C.RECORD_TYPE,
    P.CURRENT_ANNUAL_ENERGY_CONSUMPTION,
    P.REMAINING_CONTRACT_TERM,
    C.CONTRACT_VERSION
FROM VSLR.RPT.T_PROJECT AS P
INNER JOIN VSLR.RPT.T_CONTRACT AS C ON P.PROJECT_ID = C.PROJECT_ID
INNER JOIN VSLR.RPT.T_CAD AS CAD ON P.PROJECT_ID = CAD.PROJECT_ID
WHERE P.SERVICE_NUMBER = '{service_number}'
>>>>>>> Stashed changes
=======
>>>>>>> Buyout_PrepayCalc
