SELECT
    P.SERVICE_NUMBER,
    C.ESCALATOR,
    CAD.SYSTEM_SIZE_ACTUAL_KW,
    CAD.SUN_HOURS_ACTUAL,
    P.RATE_PER_KWH,
    P.START_BILLING,
    C.RECORD_TYPE,
    P.CURRENT_ANNUAL_ENERGY_CONSUMPTION,
    P.REMAINING_CONTRACT_TERM,
    C.CONTRACT_VERSION
FROM VSLR.RPT.T_PROJECT AS P
INNER JOIN VSLR.RPT.T_CONTRACT AS C ON P.PROJECT_ID = C.PROJECT_ID
INNER JOIN VSLR.RPT.T_CAD AS CAD ON P.PROJECT_ID = CAD.PROJECT_ID
WHERE P.SERVICE_NUMBER = '{service_number}'
