SELECT
      P.SERVICE_NUMBER,
      D.ESCALATOR,
      D.SYSTEM_SIZE_ACTUAL,
      D.SUN_HOURS_ACTUAL,
      P.RATE_PER_KWH,
      D.START_BILLING,
      CO.RECORD_TYPE,
      D.CURRENT_ANNUAL_ENERGY_USAGE,
      D.REMAINING_CONTRACT_TERM,
      D.CONTRACT_VERSION
FROM SFRPT.MV_SYSTEM_DETAILS D
INNER JOIN SFRPT.T_DM_PROJECT P ON D.PROJECT_NAME = P.PROJECT_NAME
INNER JOIN SFRPT.T_DM_CONTRACT CO ON D.PROJECT_ID = CO.PROJECT_ID
WHERE P.SERVICE_NUMBER = :serviceNum;