SELECT T.SERVICE_NAME,
      C.FULL_NAME,
      C.EMAIL,
      T.SERVICE_ADDRESS,
      T.SERVICE_CITY,
      T.SERVICE_STATE,
      T.SERVICE_ZIP_CODE,
      T.START_BILLING
FROM VSLR.RPT.T_PROJECT AS T
INNER JOIN VSLR.RPT.T_CONTACT AS C
      ON C.CONTACT_ID = T.CONTRACT_SIGNER
      WHERE T.SERVICE_NUMBER = '{service_number}';

SELECT DISTINCT
        P.SERVICE_NUMBER,
        TO_CHAR(NVL(ESC.ESC_SCHEDULED_FOR, ESC.UPGRADE_SCHEDULED_FOR),'Mon DD, YYYY HH24:MI:SS') ESC_SCHEDULED_FOR,
        I.ARRAYS,
        C.SYSTEM_SIZE_DESIGNED_KW,
        C.MODULE_QTY,
        C.ROOF_TYPE,
        C.INVERTER_MANUFACTURER,
        C.INVERTER_MODEL,
        C.TOTAL_SOLAR_ROOFS,
        ROOF.ROOF_TILT,
        ROOF.ROOF_AZIMUTH,
        ROOF.NUM_MODULES_DESIGNED
FROM VSLR.RPT.T_CAD AS C
INNER JOIN VSLR.RPT.T_PROJECT AS P ON C.CAD_ID = P.PRIMARY_CAD
LEFT JOIN VSLR.RPT.T_IDM AS I ON P.SERVICE_NUMBER = I.SERVICE_NUMBER
LEFT JOIN (
            SELECT *
            FROM VSLR.RPT.T_CASE AS C
            WHERE C.RECORD_TYPE = 'Solar - Electrical Service Change'
          ) AS ESC ON P.PROJECT_ID = ESC.PROJECT_ID
LEFT JOIN VSLR.COBBLESTONE.V_PAY_LOAD_ROOF_SECTION AS CO ON P.SERVICE_NUMBER = CO.SERVICE
LEFT JOIN VSLR.RPT.V_CAD_ROOF_CONFIGURATIONS AS ROOF ON C.CAD_ID = ROOF.CAD_ID
WHERE P.SERVICE_NUMBER = '{service_number}';