SELECT
    T.SERVICE_NAME,
    C.FULL_NAME,
    C.EMAIL,
    T.SERVICE_ADDRESS,
    T.SERVICE_CITY,
    T.SERVICE_STATE,
    T.SERVICE_ZIP_CODE,
    DATE_TRUNC('D', T.START_BILLING),
    T.UTILITY_COMPANY,
    U.BLENDED_RATE,
    M.RECORD_TYPE
FROM VSLR.RPT.T_PROJECT AS T
INNER JOIN VSLR.RPT.T_CONTACT AS C ON C.CONTACT_ID = T.CONTRACT_SIGNER
LEFT JOIN VSLR.D_POST_INSTALL.T_UTILITY_MATCH AS X ON UPPER(X.SF_UTILITY_NAME) = UPPER(T.UTILITY_COMPANY) AND X.SF_STATE = T.SERVICE_STATE
INNER JOIN VSLR.D_POST_INSTALL.T_UTILITY_RATES_SUMMARY AS U ON U.STATE = X.CM_STATE AND UPPER(U.UTILITY) = UPPER(X.CM_UTILITY_NAME)
LEFT JOIN VSLR.RPT.T_CONTRACT AS M ON T.PRIMARY_CONTRACT_ID = M.CONTRACT_ID
WHERE T.PROJECT_STATUS != 'Cancelled'
AND T.SERVICE_NUMBER = '{service_number}';

SELECT
      TO_CHAR(T.READ_DATE, 'MON YYYY') AS "Month Year",
      T.ACTUAL_KWH AS "Actual (kWh)",
      NVL(COALESCE (P.RATE_PER_KWH * POWER(1.029,TRUNC(DATEDIFF(DAY, DATE_TRUNC('D', P.START_BILLING), DATE_TRUNC('D', T.READ_DATE)) / 365)), T.CURRENT_RATE_KWH), 0) AS "PPA/Lease rate per kWh",
      ROUND(T.ACTUAL_KWH * NVL(COALESCE(P.RATE_PER_KWH * POWER(1.029, TRUNC(DATEDIFF('D', DATE_TRUNC('D', P.START_BILLING), DATE_TRUNC('D', T.READ_DATE)) / 365)),T.CURRENT_RATE_KWH), 0), 2) AS "Vivint Solar Bill",
      ROUND(T.ACTUAL_KWH * COALESCE (U.BLENDED_RATE, U.VSLR_CALCULATED_RATE), 2) AS "Utility Bill",
      ROUND(T.ACTUAL_KWH * (COALESCE (U.BLENDED_RATE, U.VSLR_CALCULATED_RATE) - NVL(COALESCE(P.RATE_PER_KWH * POWER(1.029, TRUNC((DATEDIFF(DAY, DATE_TRUNC('D', P.START_BILLING), DATE_TRUNC('D', T.READ_DATE))) / 365)), T.CURRENT_RATE_KWH), 0)), 2) AS "Savings"
FROM VSLR.FLEET.T_DAILY_ENERGY_WA AS T
INNER JOIN VSLR.RPT.T_PROJECT AS P ON P.PROJECT_ID = T.PROJECT_ID
LEFT JOIN VSLR.D_POST_INSTALL.T_UTILITY_MATCH AS X ON UPPER(X.SF_UTILITY_NAME) = UPPER(P.UTILITY_COMPANY) AND X.SF_STATE = P.SERVICE_STATE
INNER JOIN VSLR.D_POST_INSTALL.T_UTILITY_RATES_SUMMARY AS U ON U.STATE = X.CM_STATE AND UPPER(U.UTILITY) = UPPER(X.CM_UTILITY_NAME)
WHERE T.LIFETIME_TOTAL_DAYS = (
                              SELECT
                                    MAX(W.LIFETIME_TOTAL_DAYS)
                              FROM VSLR.FLEET.T_DAILY_ENERGY_WA AS W
                              WHERE W.PROJECT_ID = T.PROJECT_ID
                              AND W.MONTH = T.MONTH
                              AND W.YEAR = T.YEAR
                              )
AND P.SERVICE_NUMBER ='{service_number}'
AND T.READ_DATE BETWEEN TO_DATE('{start_date}', 'MM/DD/YYYY') AND TO_DATE('{end_date}', 'MM/DD/YYYY')
ORDER BY T.READ_DATE