SELECT
    T.SERVICE_NAME,
    t.SERVICE_NUMBER
FROM VSLR.RPT.T_PROJECT AS T
INNER JOIN VSLR.RPT.T_CONTACT AS C ON C.CONTACT_ID = T.CONTRACT_SIGNER
LEFT JOIN VSLR.D_POST_INSTALL.T_UTILITY_MATCH AS X ON UPPER(X.SF_UTILITY_NAME) = UPPER(T.UTILITY_COMPANY) AND X.SF_STATE = T.SERVICE_STATE
INNER JOIN VSLR.D_POST_INSTALL.T_UTILITY_RATES_SUMMARY AS U ON U.STATE = X.CM_STATE AND UPPER(U.UTILITY) = UPPER(X.CM_UTILITY_NAME)
LEFT JOIN VSLR.RPT.T_CONTRACT AS M ON T.PRIMARY_CONTRACT_ID = M.CONTRACT_ID
WHERE T.PROJECT_STATUS != 'Cancelled'
AND T.SERVICE_NUMBER = '{service_number}';
SELECT
      p.SERVICE_NUMBER
FROM VSLR.FLEET.T_DAILY_ENERGY_WA AS T
INNER JOIN VSLR.RPT.T_PROJECT AS P ON P.PROJECT_ID = T.PROJECT_ID
LEFT JOIN VSLR.D_POST_INSTALL.T_UTILITY_MATCH AS X ON UPPER(X.SF_UTILITY_NAME) = UPPER(P.UTILITY_COMPANY) AND X.SF_STATE = P.SERVICE_STATE
INNER JOIN VSLR.D_POST_INSTALL.T_UTILITY_RATES_SUMMARY AS U ON U.STATE = X.CM_STATE AND UPPER(U.UTILITY) = UPPER(X.CM_UTILITY_NAME)
WHERE T.LIFETIME_TOTAL_DAYS = (
                              SELECT
                                    MAX(W.LIFETIME_TOTAL_DAYS)
                              FROM VSLR.FLEET.T_DAILY_ENERGY_WA AS W
                              WHERE W.PROJECT_ID = T.PROJECT_ID
                              AND W.MONTH = T.MONTH
                              AND W.YEAR = T.YEAR
                              )
ORDER BY T.READ_DATE