SELECT
      T.SERVICE_NAME,
      INITCAP(C.FULL_NAME),
      C.PHONE,
      INITCAP(C.EMAIL),
      INITCAP(T.SERVICE_ADDRESS),
      INITCAP(T.SERVICE_CITY),
      T.SERVICE_STATE,
      T.SERVICE_ZIP_CODE
FROM VSLR.RPT.T_PROJECT AS T
INNER JOIN VSLR.RPT.T_CONTACT AS C
      ON C.CONTACT_ID = T.CONTRACT_SIGNER
      WHERE T.SERVICE_NUMBER = '{service_number}';

SELECT
      --APPROVED BY NEED TO GET FROM HR
      P.PTO_AWARDED, --IF DATE, IT'S POST PTO
      CA.RECORD_TYPE,
      P.SERVICE_NUMBER,
      C.SYSTEM_SIZE_ACTUAL_KW,
      C.TOTAL_MODULES_DESIGNED,
      CA.REQUESTED_MODULES_TO_BE_REMOVED,
      CA.PARTIAL_OR_COMPLETE,
      I.TILT,
      R.AZIMUTH,
      I.INVERTER,
      CA.RACKING_TYPE,
      C.MODULE_MANUFACTURER,
      C.MODULE_MODEL
      --DATE APPROVED

FROM VSLR.RPT.T_WORKORDER AS W
INNER JOIN VSLR.RPT.T_PROJECT AS P ON W.PROJECT_ID = P.PROJECT_ID
INNER JOIN VSLR.RPT.T_CAD AS C ON P.PROJECT_ID = C.PROJECT_ID
INNER JOIN VSLR.RPT.T_IDM AS I ON I.PROJECT_ID = C.PROJECT_ID
INNER JOIN VSLR.COBBLESTONE.V_PAY_LOAD_ROOF_SECTION AS R ON R.SERVICE = P.SERVICE_NUMBER
INNER JOIN VSLR.RPT.T_CASE AS CA ON CA.PROJECT_ID = P.PROJECT_ID
WHERE CA.RECORD_TYPE = 'Solar - Panel Removal';
;