SELECT
      T.SERVICE_NAME,
      C.FULL_NAME,
      C.EMAIL,
      T.SERVICE_ADDRESS,
      T.SERVICE_CITY,
      T.SERVICE_STATE,
      T.SERVICE_ZIP_CODE,
      T.START_BILLING
FROM VSLR.RPT.T_PROJECT AS T
INNER JOIN VSLR.RPT.T_CONTACT AS C
      ON C.CONTACT_ID = T.CONTRACT_SIGNER
      WHERE T.SERVICE_NUMBER = %s;

SELECT
      --APPROVED BY NEED TO GET FROM HR
      P.PTO_AWARDED, --IF DATE, IT'S POST PTO
      CA.RECORD_TYPE,
      P.SERVICE_NUMBER,
      C.SYSTEM_SIZE_ACTUAL_KW,
      C.TOTAL_MODULES_DESIGNED,
      --NUMBER OF MODULES REMOVED
      --AFFECTED ROOF SECTION, NEED TO CHOOSE?
      I.TILT,
      R.AZIMUTH,
      I.INVERTER,
      --NO ACCESS TO RACKING SYSTEM
      C.MODULE_MANUFACTURER,
      C.MODULE_MODEL
      --DATE APPROVED

FROM VSLR.RPT.T_WORKORDER AS W
INNER JOIN VSLR.RPT.T_PROJECT AS P ON W.PROJECT_ID = P.PROJECT_ID
INNER JOIN VSLR.RPT.T_CAD AS C ON P.PROJECT_ID = C.PROJECT_ID
INNER JOIN VSLR.RPT.T_IDM AS I ON I.PROJECT_ID = C.PROJECT_ID
INNER JOIN VSLR.COBBLESTONE.V_PAY_LOAD_ROOF_SECTION AS R ON R.SERVICE = P.SERVICE_NUMBER
INNER JOIN VSLR.RPT.T_CASE AS CA ON CA.PROJECT_ID = P.PROJECT_ID
WHERE CA.RECORD_TYPE = 'Solar - Panel Removal';
;