# Generated by Django 2.0.7 on 2018-08-13 17:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee_id',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('badgeid', models.IntegerField()),
                ('allotment', models.IntegerField()),
                ('edited', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anonymous', models.IntegerField(default=0)),
                ('bad_comment', models.IntegerField(default=0)),
                ('benefactor', models.IntegerField()),
                ('benefactor_name', models.CharField(default='To Be Filled in Later', max_length=100)),
                ('recipient', models.IntegerField()),
                ('recipient_name', models.CharField(default='To Be Filled in Later', max_length=100)),
                ('award', models.IntegerField()),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
