# Generated by Django 2.0.7 on 2018-08-13 20:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_id',
            name='edited',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 13, 14, 54, 28, 618260)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 13, 14, 54, 28, 618260)),
        ),
    ]
