# Generated by Django 2.0.7 on 2018-08-08 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee_id',
            old_name='give',
            new_name='allotment',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='from_id',
            new_name='award',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='gave',
            new_name='benefactor',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='to_id',
            new_name='recipient',
        ),
    ]
