# Generated by Django 2.0.7 on 2018-08-09 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0002_auto_20180808_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='benefactor_name',
            field=models.CharField(default='To Be Filled in Later', max_length=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='recipient_name',
            field=models.CharField(default='To Be Filled in Later', max_length=100),
        ),
    ]
