# Generated by Django 2.0.7 on 2018-08-13 21:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0002_auto_20180813_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_id',
            name='edited',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 13, 21, 14, 5, 15839, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 13, 21, 14, 5, 15839, tzinfo=utc)),
        ),
    ]
