# Generated by Django 2.0.7 on 2018-08-13 21:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0004_auto_20180813_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_id',
            name='edited',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 8, 13, 21, 15, 4, 249614, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 8, 13, 15, 15, 4, 249614)),
        ),
    ]
