# Generated by Django 2.0.7 on 2018-08-13 21:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0005_auto_20180813_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_id',
            name='edited',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 8, 13, 21, 31, 15, 348830, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 8, 13, 21, 31, 15, 365469, tzinfo=utc)),
        ),
    ]
