# Generated by Django 2.0.7 on 2018-08-13 21:34

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0006_auto_20180813_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_id',
            name='edited',
            field=models.DateTimeField(verbose_name=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 8, 13, 21, 34, 36, 363938, tzinfo=utc)),
        ),
    ]
