# Generated by Django 2.0.7 on 2018-08-13 21:36

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0007_auto_20180813_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_id',
            name='edited',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 13, 21, 36, 35, 744648, tzinfo=utc)),
        ),
    ]
