SELECT W.FULL_NAME, W.BADGE_ID, TERMINATION_DATE
FROM WORKDAY.V_WORKDAY_CURRENT_V2 W
WHERE W.WORK_EMAIL_ADDRESS != 'NULL'
AND TERMINATED = 1
AND trunc(W.TERMINATION_DATE) < trunc(current_date)
and trunc(W.TERMINATION_DATE) >= trunc(current_date -7)
    AND (COST_CENTER_ID = '3400'
         OR COST_CENTER_ID = '3470'
         or COST_CENTER_ID = '3700')
ORDER BY W.TERMINATION_DATE DESC