    SELECT
FULL_NAME
, BADGE_ID
FROM VSLR.HR.T_EMPLOYEE
-- AND TERMINATION_DATE < TRUNC(CURRENT_DATE, 'DAY' )
-- AND TERMINATION_DATE >= DATEADD(DAY, -7, CURRENT_DATE)
    WHERE
      (TERMINATED = 1
      AND WORK_EMAIL_ADDRESS != 'NULL'
      AND MGR_ID_3 = 209122 --CHUCK'S BADGE ID
      AND MGR_ID_4 != 111594 --CHARLES HENDERSON'S BADGE ID
      AND BADGE_ID != 111594)
      ;
-- AND (COST_CENTER_ID = '3400'
--       OR COST_CENTER_ID = '3470'
--       OR COST_CENTER_ID = '3700')