SELECT W.FULL_NAME, W.BADGE_ID, TERMINATION_DATE
FROM WORKDAY.V_WORKDAY_CURRENT_V2 W
WHERE W.WORK_EMAIL_ADDRESS != 'NULL'
AND TERMINATED = 1
AND trunc(W.TERMINATION_DATE) < trunc(current_date)
and trunc(W.TERMINATION_DATE) >= trunc(current_date -7)
    AND (COST_CENTER_ID = '3400'
         OR COST_CENTER_ID = '3470'
         or COST_CENTER_ID = '3700')
ORDER BY W.TERMINATION_DATE DESC

-- --SNOWFLAKE
-- SELECT FULL_NAME, BADGE_ID, TERMINATION_DATE
-- FROM VSLR.HR.T_EMPLOYEE
-- WHERE WORK_EMAIL_ADDRESS != 'NULL'
-- AND TERMINATED = 1
-- AND TERMINATION_DATE < TRUNC(CURRENT_DATE, 'DAY' )
-- AND TERMINATION_DATE >= DATEADD(DAY, -7, CURRENT_DATE)
-- AND (COST_CENTER_ID = '3400'
--       OR COST_CENTER_ID = '3470'
--       OR COST_CENTER_ID = '3700')
-- ORDER BY TERMINATION_DATE DESC