-- SELECT W.BADGE_ID, W.FULL_NAME
-- FROM WORKDAY.V_WORKDAY_CURRENT_V2 W
-- WHERE W.TERMINATED = '0'
-- AND W.WORK_EMAIL_ADDRESS != 'NULL'
-- AND (COST_CENTER_ID = '3400'
--     OR COST_CENTER_ID = '3470'
--     or COST_CENTER_ID = '3700')
--     OR BADGE_ID = 112741)
--
-- ORDER BY W.FULL_NAME;

-- -- SNOWFLAKE
SELECT BADGE_ID, FULL_NAME
FROM VSLR.HR.T_EMPLOYEE
WHERE TERMINATED = 0
AND WORK_EMAIL_ADDRESS != 'NULL'
AND (COST_CENTER_ID = '3400'
      OR COST_CENTER_ID = '3470'
      OR COST_CENTER_ID = '3700'
      OR BADGE_ID = 112741)
ORDER BY FULL_NAME