SELECT BADGE_ID, FULL_NAME
FROM VSLR.HR.T_EMPLOYEE
WHERE TERMINATED = 0
AND WORK_EMAIL_ADDRESS != 'NULL'
AND (COST_CENTER_ID = '3400'
      OR COST_CENTER_ID = '3470'
      OR COST_CENTER_ID = '3700'
      OR BADGE_ID = 112741)
ORDER BY FULL_NAME